version: '3'

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"  # Map PostgreSQL port

  python_app:
    build:
      context: ./python
    ports:
      - "80:80"  # Map the port used in the Python app container
    depends_on:
      - postgres  # Ensure PostgreSQL container is started first
