FROM mongo

# # Install additional packages, including the MongoDB clients
# RUN apt-get update && apt-get install -y \
#     mongodb-clients \
#     # Add any other packages you may need here \
#     && rm -rf /var/lib/apt/lists/*